### ISSUE TITLE
Head index of smplx vert segmentation did not exist

### ISSUE THREAD

**Issue by sumingrui** [Meshcapade/wiki#1]
Hi, I found that head index in wiki/assets/SMPL_body_segmentation/smplx/smplx_vert_segmentation.json is empty. Could you please tell me how to get it, thank you.

**Comment by raincrash** [comment]
Hey @sumingrui. I have updated the JSON. Thanks for raising the issue. 

Closing this.

**Comment by tommycwh** [comment]
Hello. I also have a question about the segmentation labels of the SMPLX model. I found 11971 labels from your JSON file, but I only got 10475 vertices from the SMPLX model (i.e., the "SMPLX_NEUTRAL" model). 

It seems that there are 1498 duplicated labels in your JSON files. For example, "10474" appears in both "eyeballs" and "righteye", and "3210" appears in both "spine2" and "neck". May I ask if this is expected? Or which should I choose among these duplicates while assigning the labels to the vertices?
